from abc import ABC, abstractmethod
from typing import Iterable

class Datamart(ABC):
    @abstractmethod
    def upsert_many(self, rows: Iterable[dict]) -> int: ...
    @abstractmethod
    def get_by_author(self, author: str) -> list[dict]: ...
    @abstractmethod
    def get_by_title(self, title: str) -> list[dict]: ...
    @abstractmethod
    def close(self) -> None: ...
